export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_LANDING_STATE = 'UPDATE_LANDING_STATE';
export const UPDATE_USER_LOGIN_STATE = 'UPDATE_USER_LOGIN_STATE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const UPDATE_SIDE_PANEL = 'UPDATE_SIDE_PANEL';
export const UPDATE_STOCK_INFO = 'UPDATE_STOCK_INFO';